In [2]:
import pandas as pd

df = pd.read_parquet("../data/processed/corpus.parquet")

# 1. Sumber gred hadis
print(df.groupby("source")["grade_source"].value_counts(dropna=False), "\n")

# 2. Nombor kitab Bukhari yang tiada tajuk
missing = df[(df.source == "bukhari") & df.chapter_title.isna()]
print(missing["book_no"].value_counts(dropna=False).head(10), "\n")

# 3. Semak isu Basmalah pada ayat pertama
df[(df.source == "quran") & (df.item_no == 1)][["ref", "text_ar"]].head(4)

source   grade_source
bukhari  collection      7580
muslim   collection      7360
quran    NaN             6236
Name: count, dtype: int64

Series([], Name: count, dtype: Int64)

     ref                                            text_ar
0    1:1             بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
7    2:1                                                الم
293  3:1                                                الم
493  4:1  يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ الَّذ...

In [2]:
b0 = df[(df.source == "bukhari") & (df.book_no == 0)].sort_values("item_no")

print(b0["item_no"].describe(), "\n")
print("Nombor perpuluhan:", (b0["item_no"] % 1 != 0).sum(), "\n")

# Adakah ia berkelompok atau bertaburan?
print(b0["item_no"].head(15).tolist())

b0[["ref", "text_en"]].head(5)

count     306.000000
mean     3631.264706
std      2084.665942
min       299.000000
25%      1926.500000
50%      3432.500000
75%      5255.250000
max      7495.000000
Name: item_no, dtype: float64

Nombor perpuluhan: 0

[299.0, 300.0, 329.0, 395.0, 408.0, 410.0, 435.0, 454.0, 478.0, 521.0, 533.0, 536.0, 570.0, 582.0, 622.0]

              ref                                            text_en
6534  Bukhari 299  Narrated `Aisha:The Prophet (ﷺ) and I used to ...
6535  Bukhari 300  Narrated `Aisha:The Prophet (ﷺ) and I used to ...
6564  Bukhari 329  Narrated Ibn `Abbas:A woman is allowed to leav...
6630  Bukhari 395  Narrated `Amr bin Dinar:I asked Ibn `Umar, "Ca...
6644  Bukhari 408  Narrated Abu Huraira and Abu Sa`id:Allah's Mes...

In [7]:
import json
from pathlib import Path

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data" / "processed").exists())

for c in ["bukhari", "muslim"]:
    with open(ROOT / "data" / "raw" / "hadith" / f"eng-{c}.json", encoding="utf-8") as f:
        d = json.load(f)
    print(c, "-> tajuk kitab 0:", repr(d["metadata"]["sections"].get("0")))

bukhari -> tajuk kitab 0: ''
muslim -> tajuk kitab 0: 'Introduction'

In [8]:
import json

for c in ["bukhari", "muslim"]:
    with open(ROOT / "data" / "raw" / "hadith" / f"eng-{c}.json", encoding="utf-8") as f:
        d = json.load(f)
    print(c, "-> tajuk kitab 0:", repr(d["metadata"]["sections"].get("0")))

bukhari -> tajuk kitab 0: ''
muslim -> tajuk kitab 0: 'Introduction'

In [9]:
df = pd.read_parquet(ROOT / "data" / "processed" / "corpus.parquet")
df[df.book_inferred][["ref", "chapter_title", "text_en"]].sample(5, random_state=1)

,ref,chapter_title,text_en
10495,Bukhari 4244,Tidak diklasifikasikan,Narrated Abu Sa`id Al-Khudri and Abu Huraira:A...
9142,Bukhari 2895,Tidak diklasifikasikan,Narrated Anas bin Malik:Um Haram told me that ...
10431,Bukhari 4180,Tidak diklasifikasikan,Narrated `Urwa bin Az-Zubair:That he heard Mar...
10775,Bukhari 4524,Tidak diklasifikasikan,"Narrated Ibn Abu Mulaika:Ibn `Abbas recited: ""..."
8748,Bukhari 2501,Tidak diklasifikasikan,Narrated `Abdullah bin Hisham:that his mother ...

In [10]:
df[(df.source == "quran") & (df.item_no == 1)][["ref", "text_ar"]].head(4)

     ref                                            text_ar
0    1:1            ﻿بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
7    2:1         بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الم
293  3:1         بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الم
493  4:1  بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ يَا أَي...

In [12]:
df = pd.read_parquet(ROOT / "data" / "processed" / "corpus.parquet")

# Bilangan "Tidak diklasifikasikan" (jangkaan: bukhari 6, muslim 0)
print(df[df.chapter_title == "Tidak diklasifikasikan"]["source"].value_counts(), "\n")

# Spot-check semula
display(df[df.book_inferred][["ref", "chapter_title", "text_en"]].sample(5, random_state=1))

# Basmalah
display(df[(df.source == "quran") & (df.item_no == 1)][["ref", "text_ar"]].head(4))

source
bukhari    7580
Name: count, dtype: int64

,ref,chapter_title,text_en
10495,Bukhari 4244,Tidak diklasifikasikan,Narrated Abu Sa`id Al-Khudri and Abu Huraira:A...
9142,Bukhari 2895,Tidak diklasifikasikan,Narrated Anas bin Malik:Um Haram told me that ...
10431,Bukhari 4180,Tidak diklasifikasikan,Narrated `Urwa bin Az-Zubair:That he heard Mar...
10775,Bukhari 4524,Tidak diklasifikasikan,"Narrated Ibn Abu Mulaika:Ibn `Abbas recited: ""..."
8748,Bukhari 2501,Tidak diklasifikasikan,Narrated `Abdullah bin Hisham:that his mother ...

     ref                                            text_ar
0    1:1            ﻿بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
7    2:1         بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الم
293  3:1         بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الم
493  4:1  بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ يَا أَي...

In [14]:
df = pd.read_parquet(ROOT / "data" / "processed" / "corpus.parquet")
display(df[df.book_inferred][["ref", "chapter_title", "text_en"]].sample(5, random_state=1))
display(df[(df.source == "quran") & (df.item_no == 1)][["ref", "text_ar", "text_ms"]].head(4))

,ref,chapter_title,text_en
10495,Bukhari 4244,Military Expeditions led by the Prophet (pbuh)...,Narrated Abu Sa`id Al-Khudri and Abu Huraira:A...
9142,Bukhari 2895,Fighting for the Cause of Allah (Jihaad),Narrated Anas bin Malik:Um Haram told me that ...
10431,Bukhari 4180,Military Expeditions led by the Prophet (pbuh)...,Narrated `Urwa bin Az-Zubair:That he heard Mar...
10775,Bukhari 4524,Prophetic Commentary on the Qur'an (Tafseer of...,"Narrated Ibn Abu Mulaika:Ibn `Abbas recited: ""..."
8748,Bukhari 2501,Partnership,Narrated `Abdullah bin Hisham:that his mother ...

,ref,text_ar,text_ms
0,1:1,بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ,"Dengan nama Allah, Yang Maha Pemurah, lagi Mah..."
7,2:1,الم,"Alif, Laam, Miim."
293,3:1,الم,"Alif, Laam, Miim."
493,4:1,يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ الَّذ...,Wahai sekalian manusia! Bertaqwalah kepada Tuh...

In [3]:
df[df.ref == "33:11"][["text_ms", "text_en"]].map(repr)

,text_ms,text_en
3543,'Pada saat itulah diuji orang-orang yang berim...,'There the believers were tested and shaken wi...

In [5]:
from pathlib import Path
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "data" / "processed").exists())

In [6]:
import glob
import pandas as pd

res = pd.read_csv(sorted(glob.glob(str(ROOT / "eval" / "results" / "*.csv")))[-1])
syn = pd.read_csv(ROOT / "eval" / "synthetic_queries.csv", encoding="utf-8-sig")
res = res.merge(syn[["query", "lang"]], on="query", how="left")
res["lang"] = res["lang"].fillna("manual")

# 1. Adakah bahasa soalan memberi kesan?
display(res[res.type != "negative"]
        .groupby(["type", "lang", "method"])["recall@10"].mean().unstack().round(3))

# 2. Berapa soalan positif yang akan tertolak jika threshold BM25 = 14?
pos_bm25 = res[(res.method == "bm25") & (res.type != "negative")]
print(f"Positif di bawah 14: {(pos_bm25.top_score < 14).mean():.1%}")

method                    bm25  dense
type             lang
manual           manual  0.478  0.159
synthetic_hadith en      1.000  0.600
                 ms      0.025  0.175
synthetic_quran  en      0.556  0.556
                 ms      0.782  0.555

Positif di bawah 14: 2.6%

In [7]:
import glob
files = sorted(glob.glob(str(ROOT / "eval" / "results" / "*.csv")))
for i, f in enumerate(files):
    print(i, Path(f).name)

0 20260929_1229_multilingual-e5-base.csv
1 20260929_1237_multilingual-e5-base.csv
2 20260929_1245_multilingual-e5-base.csv
3 20260929_1246_multilingual-e5-base_w2.csv
4 20260929_2302_multilingual-e5-base_sections.csv

In [9]:
untagged = [f for f in files if Path(f).stem.endswith("multilingual-e5-base")]
v2_file = next(f for f in reversed(untagged) if "hybrid" in pd.read_csv(f)["method"].values)
print("v2:", Path(v2_file).name)
print("v3:", Path(files[-1]).name)

old = pd.read_csv(v2_file)
new = pd.read_csv(files[-1])

cols = ["qid", "query", "recall@10", "top_ref"]
o = old[(old.method == "hybrid") & (old.type == "synthetic_quran")][cols]
n = new[(new.method == "hybrid") & (new.type == "synthetic_quran")][["qid", "recall@10", "top_ref"]]
m = o.merge(n, on="qid", suffixes=("_v2", "_v3"))

print("Lebih baik di v3:", (m["recall@10_v3"] > m["recall@10_v2"]).sum())
print("Lebih teruk di v3:", (m["recall@10_v3"] < m["recall@10_v2"]).sum())
m[m["recall@10_v3"] != m["recall@10_v2"]]

v2: 20260929_1245_multilingual-e5-base.csv
v3: 20260929_2302_multilingual-e5-base_sections.csv
Lebih baik di v3: 0
Lebih teruk di v3: 5

,qid,query,recall@10_v2,top_ref_v2,recall@10_v3,top_ref_v3
1,q0001,manusia tidak boleh lari dari kuasa Allah wala...,1.0,18:43,0.0,22:8
7,q0007,syurga Adn tempat Allah reda kepada mereka dan...,1.0,47:6,0.0,47:6
33,q0033,Nabi Ibrahim bersumpah akan bertindak terhadap...,1.0,15:51,0.0,15:51
39,q0039,menyerahkan segala urusan kepada Allah yang me...,1.0,53:25,0.0,53:25
72,q0072,syurga dengan pasangan yang suci dan naungan y...,1.0,77:41,0.0,77:41